### ISSUE TITLE
How to compile on a modern mac

### ISSUE THREAD

**Issue by thegodone** [greglandrum/yaehmop#19]
I try to figure out how to compile the bind program, but I have issue with old dependencies:

MacBook-Pro:tightbind GVALMTGG$ make
cc -g  -I/usr/local/include/ -DEHT_PARM_FILE=\"//Users/GVALMTGG/Downloads/yaehmop-master/tightbind/eht_parms.dat\" -DUNDERSCORE_FORTRAN -DANAL_ABOUT_PROTOTYPES -c main.c
In file included from main.c:55:
./bind.h:97:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
 
I replace malloc.h by  stdlib.h as suggested by Greg 👍

it helps but now I have this g2c lib issue:
cc -o bind -g  -I/usr/local/include/ -DEHT_PARM_FILE=\"//Users/GVALMTGG/Downloads/yaehmop-master/tightbind/eht_parms.dat\" -DUNDERSCORE_FORTRAN -DANAL_ABOUT_PROTOTYPES main.o genutil.o fileio.o globals.o memory.o distance_mat.o R_overlap_mat.o mov.o R_hamil.o K_hamil.o kpoints.o K_overlap_mat.o mulliken.o charge_mat.o zetas.o electrostat.o new3_fileio.o walsh.o transforms.o symmetry.o princ_axes.o avg_props.o DOS_stuff.o COOP_stuff.o Zmat.o bands.o FMO_stuff.o xtal_coords.o matrices.o chg_it.o mod_mulliken.o postprocess.o muller.o geom_frags.o solid_symmetry.o recip_space.o netCDF_support.o lovlap.o abfns.o cboris.o diag.o   -lm /Users/GVALMTGG/Downloads/ilupackV2.2_macosx64_long/lib/MACOSX64_long/liblapack.a /Users/GVALMTGG/Downloads/ilupackV2.2_macosx64_long/lib/MACOSX64_long/libblas.a -lg2c
ld: library not found for -lg2c
clang: error: linker command failed with exit code 1 (use -v to see invocation)

last step is to replace -lg2c by -lf2c in the makefile (LOCALLIBS parameter)

please @psavery can you add that to the documentation please

**Comment by thegodone** [comment]
I try the example in the pdf doc but got this error message

MacBook-Pro:tightbind GVALMTGG$ ./bind
Usage: bind <inputfile> [paramfile]
MacBook-Pro:tightbind GVALMTGG$ ./bind ethane.bind eht_parms.dat
Welcome to the 10th Anniversary edition of YAeHMOP!
Segmentation fault: 11
MacBook-Pro:tightbind GVALMTGG$ ./bind ethane.bind eht_parms.h
Welcome to the 10th Anniversary edition of YAeHMOP!
Can't find parameters for atom: H
FATAL ERROR: Parameter acquisition failure :-(.
Execution Terminated.

**Comment by psavery** [comment]
Hi @thegodone,

When we started using yaehmop for avogadro, I made a CMakeLists.txt file in the `tightbind/` directory so that we can generate makefiles using cmake.

You can build it like this:
```
$ cd tightbind
$ mkdir build
$ cd build
$ cmake ..
$ make
```

However, you may need to pass a few options to cmake to get it to work properly. For instance, it uses F2C by default (you can probably install f2c with homebrew or macports). But if you want to use a fortran compiler instead (like gfortran), make sure gfortran is installed on your mac, and you can execute the cmake command like this:

```
$ cmake .. -DUSE_F2C=OFF
```

You can also link to blas and lapack with these options:

```
$ cmake .. -DUSE_F2C=OFF -DUSE_BLAS_LAPACK=ON
```

But then cmake needs to be able to find blas and lapack.

Anyways, I have some pre-compiled static binaries here (that use blas and lapack) in case you want to try them out: https://github.com/psavery/yaehmop/releases/tag/3.0.3

Patrick
